### ISSUE TITLE
paper-toggle-buttons wrong colour

### ISSUE THREAD

**Issue by mjkl-gh** [bbbenji/synthwave-hass#13]
![image](https://user-images.githubusercontent.com/9350991/68161424-284e4800-ff56-11e9-95b1-2bf0a1041695.png)

For some reason when paper toggle's are turned on Hassio makes them the background colour, making it next to impossible to make them out. I hop you guys can spot the top 2 

I've tried changing the colours and redownloading but the problem persists. It appears only when a toggle is turned off.

Same goes for a slider?
![image](https://user-images.githubusercontent.com/9350991/68161553-60558b00-ff56-11e9-8834-7fa86aacd79c.png)

When a light is fully on the slider even becomes invisible

**Comment by bbbenji** [comment]
Fixed via https://github.com/bbbenji/synthwave-hass/pull/14

**Comment by bbbenji** [comment]
Actually, partially fixed. The slider handle still needs styling.

**Comment by bbbenji** [comment]
Slider handles fixed via https://github.com/bbbenji/synthwave-hass/commit/0b0cec6e2ab7a1368aa2539dd5a3e5e9b67c2c1f

**Comment by Nephiel** [comment]
Issue still present here:
![screenshot_2019-11-27-21:09:40-Selection_001](https://user-images.githubusercontent.com/2184015/69756266-56403a00-115a-11ea-8c18-adf862673a74.png)

**Comment by bbbenji** [comment]
What version are you running? Also please clear your cache. Perhaps the old version is still being served.

**Comment by Nephiel** [comment]
> What version are you running? Also please clear your cache. Perhaps the old version is still being served.

Latest master of synthwave-hass and synthwave-hass-extras, HA 0.101.0.dev20191005 on Docker.
Logging in from a new, clean incognito session each time. Already tried restarting HA, nginx, and the whole server. Still, the issue persists.

**Comment by Nephiel** [comment]
Updated to HA 0.102 and it is indeed fixed. Thanks!

**Comment by CyanoFresh** [comment]
0.106.2, same issue:
![image](https://user-images.githubusercontent.com/4249082/75730403-7b15f180-5cf5-11ea-901a-e98d0ab659d9.png)

**Comment by mjkl-gh** [comment]
This is a different issue, The colour has changed for when the switch is off
